name: ci

on:
  push:
    branches: main

jobs:
  GHCR:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io/borninthedark/zero-two
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            borninthedark/zero-two:latest
            borninthedark/zero-two:1.0.0
            ghcr.io/borninthedark/zero-two:latest
            ghcr.io/borninthedark/zero-two:1.0.0